version: '3'
services:
  flask:
    image: pelegov/flaskls
    container_name: flask
    expose:
      - "5000"
    ports:
      - "8000"
  nginx:
    image: pelegov/nginx_proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
    depends_on:
      - flask